services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: tsp-cpp-backend
    ports:
      - "8080:8080"
    networks:
      - tsp-network
    volumes:
      - .:/workspace:cached
      - /workspace/backend/build
    working_dir: /workspace
    command: sh -c "while sleep 1000; do :; done"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tsp-angular-frontend
    ports:
      - "4200:4200"
    networks:
      - tsp-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: ng serve --host 0.0.0.0 --allowed-hosts=all --poll 2000

networks:
  tsp-network:
    driver: bridge